# Generated by Django 5.2.9 on 2025-12-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_mobile', models.BigIntegerField()),
                ('emp_salary', models.IntegerField()),
            ],
        ),
    ]
